export const ROOMS = [
{id:'ciencias',name:'Ciências',tag:'LABORATÓRIO',color:0x65d9bc,x:-22,z:-22,text:'Matéria e energia, hereditariedade, evolução e biodiversidade.\nO Observatório conecta esta sala ao Sistema Solar.',items:['Átomos e moléculas','Luz e radiações','Hereditariedade e evolução','Sistema Solar'],prop:'atom'},
{id:'matematica',name:'Matemática',tag:'ATELIÊ',color:0xf4bc65,x:22,z:-22,text:'Construa figuras e investigue relações.\nPitágoras, semelhança, funções, medidas e estatística.',items:['Teorema de Pitágoras','Semelhança e proporcionalidade','Funções e álgebra','Medidas e estatística'],prop:'geometry'},
{id:'portugues',name:'Português',tag:'REDAÇÃO E MÍDIAS',color:0xc29bea,x:-25,z:-2,text:'Leia, crie e argumente.\nUma redação para investigar fontes, construir narrativas e discutir ideias.',items:['Leitura e literatura','Produção de textos','Argumentação e fontes','Análise da linguagem'],prop:'books'},
{id:'ingles',name:'Inglês',tag:'ESTÚDIO DE IDIOMAS',color:0x84c8f2,x:25,z:-2,text:'Use o inglês em situações contextualizadas.\nDiálogos, leitura, produção e comunicação intercultural.',items:['Compreensão e produção','Argumentação','Comunicação intercultural'],prop:'globe'},
{id:'arte',name:'Arte',tag:'GALERIA',color:0xf098ac,x:-25,z:18,text:'Experimente formas, cores, sons e movimentos.\nArtes visuais, música, dança e teatro se encontram aqui.',items:['Artes visuais','Música','Dança e teatro','Criação integrada'],prop:'sculpture'},
{id:'geografia',name:'Geografia',tag:'ATLAS',color:0x91d6a2,x:25,z:18,text:'Investigue o mundo e suas conexões.\nMapas, globalização, população, economia e ambiente.',items:['Espaço mundial','Globalização','População e economia','Mapas e ambiente'],prop:'globe'},
{id:'historia',name:'História',tag:'MUSEU',color:0xd5a77e,x:-22,z:38,text:'Examine fontes e compare interpretações.\nBrasil republicano e transformações dos séculos XX e XXI.',items:['Brasil republicano','Conflitos e transformações','Direitos e cidadania'],prop:'timeline'},
{id:'educacaofisica',name:'Educação Física',tag:'ARENA',color:0xf0d880,x:22,z:38,text:'Explore práticas corporais, movimentos e estratégias.\nA experiência virtual complementa as atividades físicas da turma.',items:['Esportes e estratégias','Práticas corporais','Cultura e movimento'],prop:'sport'},
{id:'etica',name:'Ética e Culturas',tag:'FÓRUM',color:0xb0bcdf,x:0,z:54,text:'Conheça perspectivas sobre crenças, valores e convivência.\nSala de Ensino Religioso, conforme a configuração da escola e matrícula facultativa.',items:['Crenças e filosofias de vida','Vida e morte','Valores e convivência'],prop:'forum'}
];
