import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { ControlesXR } from './controles.js';
import { Painel } from './painel.js';
import { ROOMS } from './data.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
const $=id=>document.getElementById(id);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');renderer.xr.setFoveation(.6);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('world').appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x263f5d);scene.fog=new THREE.Fog(0x263f5d,95,300);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.05,1200),rig=new THREE.Group();rig.add(camera);scene.add(rig);camera.position.set(63,46,92);
scene.add(new THREE.HemisphereLight(0xcfeaff,0x405766,2.4));const sun=new THREE.DirectionalLight(0xffd4a0,3.5);sun.position.set(-50,90,-40);scene.add(sun);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.target.set(0,3,-4);orbit.minPolarAngle=.1;orbit.maxPolarAngle=Math.PI*.48;orbit.minDistance=20;orbit.maxDistance=190;
const campus=new THREE.Group();scene.add(campus);
const targets=[],solids=[],props=[],pads=[],roomGroups=new Map();
let state={mode:'overview',place:'campus',room:null,stage:'campus',sound:false,launchTime:0,hover:null};
let progress={visited:[],launch:false};try{progress={...progress,...JSON.parse(localStorage.getItem('escola-mundos.progress')||'{}')}}catch{}
function save(){try{localStorage.setItem('escola-mundos.progress',JSON.stringify(progress))}catch{}$('progressLabel').textContent=`${progress.visited.length} / 9 salas visitadas`}
const mats=new Map();function mat(color,metal=0,rough=.7){const k=`${color}:${metal}:${rough}`;if(!mats.has(k))mats.set(k,new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough}));return mats.get(k)}
function mesh(geo,color,parent=campus,x=0,y=0,z=0,metal=0){const m=new THREE.Mesh(geo,mat(color,metal));m.position.set(x,y,z);parent.add(m);return m}
function box(w,h,d,color,parent=campus,x=0,y=0,z=0,solid=false){const m=mesh(new THREE.BoxGeometry(w,h,d),color,parent,x,y,z);if(solid)solids.push(m);return m}
function cyl(r1,r2,h,color,parent=campus,x=0,y=0,z=0){return mesh(new THREE.CylinderGeometry(r1,r2,h,24),color,parent,x,y,z)}
function sign(text,color=0x8bede3,w=5,h=1.1,parent=campus,x=0,y=0,z=0,id=null){const c=document.createElement('canvas');c.width=1024;c.height=224;const ctx=c.getContext('2d');ctx.fillStyle='#0b2238';ctx.fillRect(0,0,1024,224);ctx.strokeStyle='#'+color.toString(16).padStart(6,'0');ctx.lineWidth=10;ctx.strokeRect(5,5,1014,214);ctx.fillStyle='#f3f9ff';ctx.textAlign='center';ctx.textBaseline='middle';let size=72;ctx.font=`600 ${size}px system-ui`;while(ctx.measureText(text).width>940){size-=2;ctx.font=`600 ${size}px system-ui`}ctx.fillText(text,512,115);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));m.position.set(x,y,z);parent.add(m);if(id){m.userData.corpoId=id;targets.push(m)}return m}
function pad(x,z,id,color=0x6ae9d7,parent=campus){const p=cyl(.75,.75,.04,color,parent,x,.075,z);p.userData.corpoId=id;targets.push(p);const ring=mesh(new THREE.TorusGeometry(.9,.025,6,32),color,parent,x,.13,z);ring.rotation.x=Math.PI/2;pads.push(ring);return p}
// Campus: a continuous walkable space with open classroom entrances.
box(180,1,180,0x263e46,campus,0,-.8,0);box(13,.16,138,0x617b81,campus,0,-.04,-7);
box(42,.16,18,0x7d9294,campus,0,-.02,10);box(9,.18,138,0xa0afb0,campus,0,.01,-7);
for(let z=-70;z<55;z+=5){box(.1,.04,2.3,0x84d8cc,campus,-4.2,.13,z);box(.1,.04,2.3,0x84d8cc,campus,4.2,.13,z)}
for(let z of [-22,-2,18,38])box(59,.12,4.5,0x8d9d9e,campus,0,.02,z);
// Twin reflecting pools, central sculpture and seating.
for(const x of [-11,11]){box(6,.4,13,0x142d3e,campus,x,.05,9);box(5.6,.06,12.6,0x337483,campus,x,.3,9);for(let z=4;z<15;z+=2)box(5.1,.02,.015,0x8ccacc,campus,x,.35,z)}
cyl(2.3,2.6,.5,0x314957,campus,0,.3,8);const sculpture=new THREE.Group();sculpture.position.set(0,3,8);campus.add(sculpture);for(let i=0;i<3;i++){const t=mesh(new THREE.TorusGeometry(1.85,.07,8,48),[0x81e4d0,0xedbb78,0x9bbad9][i],sculpture);t.rotation.set(i*.7,i*.9,.4)}props.push(sculpture);
function tree(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);campus.add(g);cyl(.18,.3,2.4,0x766957,g,0,1.2,0);mesh(new THREE.IcosahedronGeometry(1.7,1),0x3d827a,g,0,3.1,0);mesh(new THREE.IcosahedronGeometry(1.3,0),0x54998a,g,.7,3.8,0)}
for(let z=-42;z<60;z+=13){tree(-39,z);tree(39,z,1.15)}for(let x of [-13,13])for(let z of [-36,-7,27,48]){tree(x,z,.7);box(3,.25,.6,0xbbad92,campus,x,.55,z+2);box(.15,.65,.5,0x2d4651,campus,x-1,.3,z+2);box(.15,.65,.5,0x2d4651,campus,x+1,.3,z+2)}
for(let x of [-7,7])for(let z=-45;z<50;z+=16){cyl(.055,.08,4.3,0xacc1c8,campus,x,2.15,z);box(.9,.1,.5,0xd6f8ef,campus,x,4.3,z)}
// Distant mountains establish depth without heavy assets.
for(let i=0;i<20;i++){const a=i/20*Math.PI*2,r=210,h=20+(i%5)*12;const m=mesh(new THREE.ConeGeometry(45,h,5),0x42566a,campus,Math.cos(a)*r,h/2-2,Math.sin(a)*r);m.rotation.y=i}
function createProp(type,g,color){const p=new THREE.Group();p.position.set(0,2.7,-1.7);g.add(p);props.push(p);
if(type==='atom'){mesh(new THREE.SphereGeometry(.65,20,12),color,p);for(let i=0;i<3;i++){const ring=mesh(new THREE.TorusGeometry(1.65,.035,6,64),0xa0d9f3,p);ring.rotation.set(i*.95,i*.7,i*.5);const e=mesh(new THREE.SphereGeometry(.13,12,8),0xe4efff,ring,1.65,0,0)}}
else if(type==='geometry'){mesh(new THREE.IcosahedronGeometry(1.3,0),color,p);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.IcosahedronGeometry(1.32,0)),new THREE.LineBasicMaterial({color:0xffffff}));p.add(edges)}
else if(type==='globe'){mesh(new THREE.SphereGeometry(1.2,32,20),0x5f9ec5,p);for(let i=0;i<7;i++){const t=mesh(new THREE.TorusGeometry(1.205,.018,4,48),color,p);t.rotation.y=i*Math.PI/7}mesh(new THREE.TorusGeometry(1.45,.035,6,48),0xc6d2d8,p).rotation.x=.4}
else if(type==='books'){for(let i=0;i<5;i++){box(1.8,.25,1.2,i%2?0xc19bdf:0x779fc3,p,0,(i-2)*.3,0).rotation.y=i*.2}}
else if(type==='sculpture'){mesh(new THREE.TorusKnotGeometry(.9,.23,64,8),color,p);}
else if(type==='sport'){mesh(new THREE.SphereGeometry(.9,24,16),color,p);for(let i=0;i<3;i++){mesh(new THREE.TorusGeometry(.905,.025,4,40),0x304050,p).rotation.set(i*1.1,i*.7,0)}}
else if(type==='timeline'){for(let i=0;i<5;i++){box(.65,1+i*.2,.65,color,p,(i-2)*.85,0,0)} }
else {for(let i=0;i<6;i++){const a=i*Math.PI/3;mesh(new THREE.SphereGeometry(.35,12,8),color,p,Math.cos(a)*1.3,0,Math.sin(a)*1.3)}mesh(new THREE.TorusGeometry(1.3,.035,6,48),0xccdef0,p).rotation.x=Math.PI/2}}
for(const r of ROOMS){const g=new THREE.Group();g.position.set(r.x,0,r.z);g.rotation.y=r.x<0?Math.PI/2:r.x>0?-Math.PI/2:Math.PI;campus.add(g);roomGroups.set(r.id,g);
box(13,.3,12,0x9aabb3,g,0,.12,0);box(13,.35,12.4,0x203b51,g,0,5.65,0);box(13,.08,.14,r.color,g,0,5.9,6.15);
box(13,5.5,.22,0x304b61,g,0,2.9,-6,true);box(.22,5.5,12,0x304b61,g,-6.5,2.9,0,true);box(.22,5.5,12,0x304b61,g,6.5,2.9,0,true);
box(4.6,4.1,.22,0x3c5b70,g,-4.2,2.2,6,true);box(4.6,4.1,.22,0x3c5b70,g,4.2,2.2,6,true);box(13,1.2,.22,0x243e54,g,0,5.05,6,true);
for(let x of [-4.2,4.2])box(3.6,1.7,.07,0x588ba4,g,x,3,6.15);sign(r.name,r.color,6.5,1.15,g,0,4.9,6.18,r.id);pad(0,7.8,r.id,r.color,g);
box(5,.8,2,0x35536b,g,0,.6,-1.7);createProp(r.prop,g,r.color);
sign(r.tag,r.color,4.8,.95,g,0,4.5,-5.84);
for(let i=0;i<r.items.length;i++){sign(r.items[i],r.color,4.8,.62,g,0,3.4-i*.72,-5.84)}
for(const x of [-4.5,4.5]){box(1.2,.14,3.4,0x83979e,g,x,1.1,-.2);for(let z of [-1,1])box(.8,.5,.8,r.color,g,x,.4,z)} }
// Launch complex and an accessible tower: boarding uses a fixed-position lift.
box(30,.55,25,0x304c62,campus,0,.2,-66);const launchPad=cyl(7,7,.4,0x192d43,campus,0,.65,-66);const lr=mesh(new THREE.TorusGeometry(6,.13,8,72),0xf0b777,campus,0,.9,-66);lr.rotation.x=Math.PI/2;
const rocket=new THREE.Group();rocket.position.set(0,1,-66);scene.add(rocket);
cyl(1.8,1.8,20,0xdce4e8,rocket,0,12,0);cyl(1.9,1.9,1,0x204758,rocket,0,7,0);cyl(1.82,1.82,1.3,0x204758,rocket,0,19,0);mesh(new THREE.ConeGeometry(1.8,5,32),0xdce4e8,rocket,0,24.5,0);
for(let i=0;i<4;i++){const a=i*Math.PI/2;const fin=box(.15,4,2.6,0x48778b,rocket,Math.cos(a)*2.3,3,Math.sin(a)*2.3);fin.rotation.y=-a+Math.PI/2;cyl(.48,.7,1.1,0x243341,rocket,Math.cos(a),1.2,Math.sin(a))}
sign('MUNDOS / 01',0x81e4d0,2.2,.52,rocket,0,14,1.83);
const tower=new THREE.Group();tower.position.set(8,0,-66);campus.add(tower);
for(let x of [-2,2])for(let z of [-2,2])box(.35,30,.35,0xa7b9c2,tower,x,15,z,true);
for(let y=1;y<30;y+=3){box(4.4,.2,4.4,0x38586b,tower,0,y,0);for(let z of [-2,2]){const brace=box(.12,4.5,.12,0x7895a7,tower,0,y+1.5,z);brace.rotation.z=.9}}
box(6.4,.25,2,0x7897a7,campus,4,23,-66);box(6.4,.15,.12,0x88c6d0,campus,4,24,-65);box(6.4,.15,.12,0x88c6d0,campus,4,24,-67);
box(5,5,4,0x2f5068,tower,0,2.5,0);box(2.6,3.6,.1,0x76d4c9,tower,0,1.8,2.1);sign('TORRE DE LANÇAMENTO',0xf0bc75,9,1.45,campus,0,5,-52,'tower');sign('EMBARQUE',0x81e4d0,3,.7,tower,0,4,2.2,'board');pad(8,-61,'board',0xf0b777);pad(0,-49,'tower',0xf0b777);
// Cockpit is a separate destination, with a large front window and in-world buttons.
const cockpit=new THREE.Group();cockpit.position.set(0,24,-66);cockpit.visible=false;scene.add(cockpit);
cyl(3.9,3.9,.15,0x16364c,cockpit,0,0,0);const shell=cyl(4,4,3.8,0x284e65,cockpit,0,1.9,0);shell.geometry.dispose();shell.geometry=new THREE.CylinderGeometry(4,4,3.8,32,1,true,Math.PI*1.28,Math.PI*1.44);shell.material=mat(0x284e65);shell.material.side=THREE.DoubleSide;
for(let y of [.15,3.8]){const ring=mesh(new THREE.TorusGeometry(3.98,.08,8,64),0x8ad9d3,cockpit,0,y,0);ring.rotation.x=Math.PI/2}
box(3.2,.45,1.2,0x102b42,cockpit,0,.85,-2.4);sign('DESTINO: SISTEMA SOLAR',0x7cd9d0,2.8,.6,cockpit,0,1.6,-3.3);sign('INICIAR LANÇAMENTO',0xf2bd73,2.5,.55,cockpit,0,.95,-2.3,'launch');
box(1.1,.35,1.2,0x698592,cockpit,0,.5,1.3);box(1.1,1.1,.2,0x355269,cockpit,0,1,1.85);sign('VOLTAR À TORRE',0x95bed3,2,.45,cockpit,0,1.5,3.1,'tower');
const starsGeo=new THREE.BufferGeometry(),starCoords=[];for(let i=0;i<1800;i++){const a=Math.random()*Math.PI*2,z=Math.random()*2-1,r=280,q=Math.sqrt(1-z*z);starCoords.push(r*q*Math.cos(a),r*z,r*q*Math.sin(a))}starsGeo.setAttribute('position',new THREE.Float32BufferAttribute(starCoords,3));const stars=new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xd7edff,size:.6}));stars.position.copy(cockpit.position);stars.visible=false;scene.add(stars);
const panel=new Painel({largura:1.35,altura:1.1,px:1024}),menu=new Painel({largura:.42,altura:.34,px:800});rig.add(panel.mesh,menu.mesh);
const fadeMesh=new THREE.Mesh(new THREE.PlaneGeometry(3,3),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:0,depthTest:false,depthWrite:false,side:THREE.DoubleSide}));fadeMesh.position.z=-.25;fadeMesh.renderOrder=100;camera.add(fadeMesh);
const clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),keys=new Set(),v=new THREE.Vector3(),tmp=new THREE.Vector3();let yaw=0,pitch=0,lookDragging=false,moved=0,down=null,toastTimer,launchTimer,launchCancelled=false;
function notify(t){$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200)}
function speak(t){if(!state.sound||!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='pt-BR';u.rate=1;speechSynthesis.speak(u)}
function setLocation(tag,title,description=''){ $('locationTag').textContent=tag;$('locationTitle').textContent=title;$('locationDescription').textContent=description; }
function showInfo(title,text,buttons=[],tag='ESCOLA DOS MUNDOS'){if(renderer.xr.isPresenting){panel.mostrar({titulo:title,texto:text,botoes:buttons.map(b=>({id:b.id,rotulo:b.label,primario:b.primary})),tamanhoTexto:40});rig.updateMatrixWorld(true);camera.getWorldPosition(v);camera.getWorldDirection(tmp);tmp.y=0;tmp.normalize();const pos=v.clone().addScaledVector(tmp,1.65);pos.y=v.y-.05;panel.mesh.position.copy(rig.worldToLocal(pos));panel.mesh.lookAt(v);}else{$('infoTitle').textContent=title;$('infoTag').textContent=tag;$('infoText').textContent=text;$('infoActions').replaceChildren();for(const b of buttons){const el=document.createElement('button');el.textContent=b.label;el.className=b.primary?'accent':'';el.onclick=()=>action(b.id);$('infoActions').appendChild(el)}$('infoDialog').showModal()}speak(text)}
function closeInfo(){panel.esconder();$('infoDialog').close()}
function updateMission(){ $('stepCampus').classList.toggle('done',progress.visited.length>0);$('stepTower').classList.toggle('done',['tower','cockpit','orbit'].includes(state.stage));$('stepCockpit').classList.toggle('done',['cockpit','orbit'].includes(state.stage));$('actionButton').textContent=state.stage==='orbit'?'Abrir Sistema Solar':state.stage==='cockpit'?'Iniciar lançamento':state.stage==='tower'?'Embarcar no foguete':'Explorar a torre';$('actionHint').textContent=state.stage==='orbit'?'Sua expedição está pronta.':state.stage==='cockpit'?'A cabine está pronta para decolar.':state.stage==='tower'?'Use o elevador para acessar a cabine.':'A torre fica ao final da alameda central.' }
function getHead(){rig.updateMatrixWorld(true);return camera.getWorldPosition(new THREE.Vector3())}
async function teleport(pos,lookAt){closeInfo();$('mapDialog').close();keys.clear();if(renderer.xr.isPresenting){fadeMesh.material.opacity=1;await new Promise(r=>setTimeout(r,180));const head=getHead();rig.position.x+=pos.x-head.x;rig.position.z+=pos.z-head.z;rig.position.y=pos.y-1.65;fadeMesh.material.opacity=0;}else{enterWalk(false);rig.position.set(0,0,0);camera.position.copy(pos);if(lookAt){const d=lookAt.clone().sub(pos);yaw=Math.atan2(-d.x,-d.z);pitch=Math.atan2(d.y,Math.hypot(d.x,d.z));camera.rotation.set(pitch,yaw,0,'YXZ')}} }
function enterWalk(hint=true){if(renderer.xr.isPresenting)return;state.mode='walk';orbit.enabled=false;document.body.classList.add('walking');$('modeLabel').textContent='CAMINHANDO';$('controlsHint').textContent='WASD / setas · Arraste para olhar · E para interagir';if(hint){camera.position.set(0,1.65,29);rig.position.set(0,0,0);yaw=0;pitch=0;camera.rotation.set(0,0,0);notify('WASD para caminhar. Arraste para olhar. E para interagir.')} }
function visitRoom(id){const r=ROOMS.find(r=>r.id===id);if(!r)return;state.room=id;state.stage='campus';state.place='room';cockpit.visible=false;restoreSky();const g=roomGroups.get(id);const pos=g.localToWorld(new THREE.Vector3(0,1.65,3.9)),look=g.localToWorld(new THREE.Vector3(0,2,-2));return teleport(pos,look).then(()=>{setLocation(r.tag,r.name);if(!progress.visited.includes(id)){progress.visited.push(id);save();notify(`${r.name} · sala descoberta`)}showInfo(r.name,r.text+'\n\nAmbiente de apresentação. As missões desta sala serão desenvolvidas na próxima etapa.',[{id:'close',label:'Explorar a sala',primary:true},{id:'tower',label:'Ir à torre'}],r.tag);updateMission()}) }
function restoreSky(){rocket.visible=true;scene.background.set(0x263f5d);scene.fog=new THREE.Fog(0x263f5d,95,300);campus.visible=true;campus.position.y=0;stars.visible=false}
function cancelLaunch(){launchCancelled=true;$('actionButton').disabled=false;clearInterval(launchTimer);state.launchTime=0;fadeMesh.material.opacity=0;$('fade').style.opacity=0}
function goTower(){cancelLaunch();state.stage='tower';state.place='tower';state.room=null;cockpit.visible=false;restoreSky();return teleport(new THREE.Vector3(8,1.65,-58),new THREE.Vector3(8,2,-66)).then(()=>{setLocation('BASE ESPACIAL','Torre de lançamento');updateMission();showInfo('Da escola ao espaço','Entre no elevador e suba até a cabine do foguete.\n\nO lançamento é uma transição lúdica para o Sistema Solar.',[{id:'board',label:'Entrar no elevador',primary:true},{id:'close',label:'Explorar a base'}])})}
function board(){cancelLaunch();state.stage='cockpit';state.place='cockpit';state.room=null;cockpit.visible=true;restoreSky();return teleport(new THREE.Vector3(0,25.65,-65.3),new THREE.Vector3(0,25.5,-70)).then(()=>{setLocation('FOGUETE MUNDOS / 01','Pronto para decolar.');updateMission();showInfo('Cabine de exploração','Destino: Sistema Solar.\n\nNo computador, você verá a subida. Em VR, uma transição suave leva ao espaço.',[{id:'launch',label:'Iniciar lançamento',primary:true},{id:'tower',label:'Descer à torre'}]);speak('Você está na cabine. Quando estiver pronto, inicie o lançamento.')})}
function launch(){if(state.stage!=='cockpit'||state.launchTime)return;closeInfo();launchCancelled=false;state.launchTime=performance.now();$('actionButton').disabled=true;let count=5;notify(`Lançamento em ${count}`);speak('Preparar para lançamento. Cinco, quatro, três, dois, um.');launchTimer=setInterval(()=>{if(launchCancelled)return;count--;if(count>0){notify(`Lançamento em ${count}`);signUpdateCountdown(count)}else{clearInterval(launchTimer);finishLaunch()}},1000)}
function signUpdateCountdown(n){if(renderer.xr.isPresenting){panel.mostrar({titulo:`Lançamento em ${n}`,texto:'Permaneça na cabine.\nDestino: Sistema Solar.',tamanhoTexto:42,botoes:[{id:'cancel',rotulo:'Cancelar'}]});positionPanel()}}
async function finishLaunch(){if(launchCancelled)return;closeInfo();if(renderer.xr.isPresenting){fadeMesh.material.opacity=1;await new Promise(r=>setTimeout(r,350))}state.stage='orbit';campus.visible=false;rocket.visible=false;scene.fog=null;scene.background.set(0x020817);stars.visible=true;state.launchTime=0;fadeMesh.material.opacity=0;$('actionButton').disabled=false;progress.launch=true;save();setLocation('EXPEDIÇÃO ESPACIAL','Chegamos ao espaço.');updateMission();showInfo('Seu próximo mundo','O Sistema Solar original está pronto para explorar.\n\nEm VR, a próxima página pede que você entre em VR novamente.',[{id:'solar',label:'Abrir Sistema Solar',primary:true},{id:'home',label:'Voltar à escola'}]);speak('Chegamos ao espaço. Abra o Sistema Solar para iniciar sua expedição.')}
async function solar(){if(renderer.xr.isPresenting)await renderer.xr.getSession().end();window.location.assign('sistema-solar.html?from=escola')}
function home(){cancelLaunch();$('actionButton').disabled=false;state.place='campus';state.stage='campus';state.room=null;cockpit.visible=false;restoreSky();return teleport(new THREE.Vector3(0,1.65,29),new THREE.Vector3(0,1.65,-15)).then(()=>{setLocation('PÁTIO CENTRAL','Explore seu próximo mundo.');updateMission()})}
function action(id){if(ROOMS.some(r=>r.id===id)){return visitRoom(id)}if(id==='tower')return goTower();else if(id==='board')return board();else if(id==='launch')return launch();else if(id==='solar')return solar();else if(id==='home')return home();else if(id==='map')showVRMap();else if(id==='help')help();else if(id==='cancel'){cancelLaunch();$('actionButton').disabled=false;closeInfo();notify('Lançamento cancelado')}else closeInfo()}
function positionPanel(){const head=getHead();camera.getWorldDirection(tmp);tmp.y=0;tmp.normalize();const p=head.clone().addScaledVector(tmp,1.65);p.y=head.y-.05;panel.mesh.position.copy(rig.worldToLocal(p));panel.mesh.lookAt(head)}
function showVRMap(){showInfo('Destinos da escola','Aponte para uma placa ou use o mapa.',[{id:'ciencias',label:'Ciências'},{id:'matematica',label:'Matemática'},{id:'tower',label:'Torre',primary:true},{id:'home',label:'Pátio'},{id:'close',label:'Fechar'}])}
function help(){showInfo('Como explorar','Computador: WASD ou setas para caminhar. Arraste para olhar. Clique nas placas ou use E.\n\nCelular: arraste para olhar e use o controle circular.\n\nPICO: analógico direito avança e gira em passos; esquerdo desloca lateralmente. Gatilho seleciona; grip teletransporta para uma sala. A/X abre o menu; B/Y volta ao pátio.',[{id:'close',label:'Começar a explorar',primary:true}])}
const xrControls=new ControlesXR(renderer,rig,camera,{alvos:()=>state.place==='cockpit'?targets.filter(m=>m.parent===cockpit):targets.filter(m=>m.parent!==cockpit),paineis:()=>[panel.mesh,menu.mesh],aoHover:id=>{state.hover=id},aoSelecionar:action,aoBotaoPainel:(p,id)=>action(id),aoGrip:id=>{if(id)action(id)},aoMenu:showVRMap,aoBotaoA:showVRMap,aoBotaoB:home,aoConectar:()=>{},velocidade:()=>state.place==='cockpit'?0:2.8});
// Grounded movement retains the original controller layout and snap turning.
xrControls._lerGamepad=function(info,dt){const gp=info.gamepad;if(!gp)return;const ax=gp.axes.length>=4?[gp.axes[2],gp.axes[3]]:[gp.axes[0]||0,gp.axes[1]||0],x=Math.abs(ax[0])>.16?ax[0]:0,y=Math.abs(ax[1])>.16?ax[1]:0;const before=rig.position.clone(),speed=state.place==='cockpit'?0:2.8;camera.getWorldDirection(tmp);tmp.y=0;tmp.normalize();if(info.mao==='left'){v.crossVectors(tmp,new THREE.Vector3(0,1,0)).normalize();rig.position.addScaledVector(v,x*speed*dt)}else{rig.position.addScaledVector(tmp,-y*speed*dt);if(Math.abs(x)>.7&&this.snapPronto){this.snapPronto=false;this._girar(x>0?-Math.PI/6:Math.PI/6)}else if(Math.abs(x)<.3)this.snapPronto=true}if(!walkable(getHead()))rig.position.copy(before);const ant=this.botoesAnt[info.indice],b=gp.buttons;for(const k of [3,4,5]){if(b[k]?.pressed&&!ant[k]){if(k===5)home();else showVRMap()}ant[k]=!!b[k]?.pressed}};
const colliders=[];campus.updateMatrixWorld(true);for(const m of solids)colliders.push(new THREE.Box3().setFromObject(m));
// Merge static geometry by material; preserve interaction surfaces and animated exhibits.
const batches=new Map(),originals=[];campus.traverse(m=>{if(!m.isMesh||targets.includes(m)||pads.includes(m)||Array.isArray(m.material))return;let a=m.parent;while(a&&a!==campus){if(props.includes(a))return;a=a.parent}if(m.material.map)return;const key=m.material.uuid;if(!batches.has(key))batches.set(key,{material:m.material,geometries:[]});batches.get(key).geometries.push(m.geometry.clone().applyMatrix4(m.matrixWorld));originals.push(m)});
for(const {material,geometries} of batches.values()){const combined=mergeGeometries(geometries,false);if(combined){const merged=new THREE.Mesh(combined,material);campus.add(merged)}for(const g of geometries)g.dispose()}for(const m of originals)m.removeFromParent();
function walkable(p){if(state.place==='cockpit')return true;if(Math.abs(p.x)>72||p.z<-84||p.z>75)return false;return !colliders.some(b=>p.x>b.min.x-.3&&p.x<b.max.x+.3&&p.z>b.min.z-.3&&p.z<b.max.z+.3)}
async function setupVR(){const b=$('vrButton');if(!window.isSecureContext){b.textContent='VR exige HTTPS';b.disabled=true;return}if(!navigator.xr){b.textContent='VR: use o PICO Browser';b.onclick=help;return}try{if(!await navigator.xr.isSessionSupported('immersive-vr')){b.textContent='VR: use o PICO Browser';b.onclick=help;return}b.textContent='Entrar em VR';b.onclick=async()=>{try{const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor','layers']});await renderer.xr.setSession(session)}catch(e){notify('Não foi possível iniciar VR. Tente novamente no PICO Browser.')}}}catch{b.textContent='VR indisponível';b.onclick=help}}
renderer.xr.addEventListener('sessionstart',()=>{orbit.enabled=false;closeInfo();$('mapDialog').close();if(document.pointerLockElement)document.exitPointerLock();document.body.classList.add('in-xr');camera.position.set(0,0,0);camera.rotation.set(0,0,0);rig.position.set(0,0,29);rig.rotation.set(0,0,0);restoreSky();cockpit.visible=false;state.place='campus';state.stage='campus';setTimeout(()=>{if(renderer.xr.isPresenting&&panel.mesh.visible)positionPanel()},900);showInfo('Bem-vindo à escola','Analógicos para caminhar.\nGatilho para selecionar uma placa.\nGrip para visitar uma sala.\nA/X para abrir o mapa.',[{id:'close',label:'Explorar',primary:true},{id:'tower',label:'Ir à torre'}])});
renderer.xr.addEventListener('sessionend',()=>{cancelLaunch();document.body.classList.remove('in-xr');menu.esconder();panel.esconder();home()});
for(const r of ROOMS){const b=document.createElement('button');b.style.setProperty('--room-color','#'+r.color.toString(16));b.textContent=r.name;const s=document.createElement('small');s.textContent=r.tag;b.appendChild(s);b.onclick=()=>visitRoom(r.id);$('mapRooms').appendChild(b)}
$('walkButton').onclick=()=>enterWalk();$('towerButton').onclick=goTower;$('mapTower').onclick=goTower;$('helpButton').onclick=help;$('homeButton').onclick=home;$('mapButton').onclick=()=>{$('mapDialog').showModal()};$('actionButton').onclick=()=>action(state.stage==='orbit'?'solar':state.stage==='cockpit'?'launch':state.stage==='tower'?'board':'tower');$('soundButton').onclick=()=>{state.sound=!state.sound;$('soundButton').textContent=state.sound?'Narração ligada':'Narração desligada';$('soundButton').setAttribute('aria-pressed',state.sound);if(state.sound)speak('Bem-vindo à Escola dos Mundos. Explore as salas e embarque para o Sistema Solar.');else window.speechSynthesis?.cancel()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
const canvas=renderer.domElement;
canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};moved=0;if(state.mode==='walk'){lookDragging=true;canvas.setPointerCapture(e.pointerId)}});
canvas.addEventListener('pointermove',e=>{if(!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;moved+=Math.abs(dx)+Math.abs(dy);if(lookDragging){yaw-=dx*.004;pitch=THREE.MathUtils.clamp(pitch-dy*.003,-1.3,1.3);camera.rotation.set(pitch,yaw,0,'YXZ')}down={x:e.clientX,y:e.clientY}});
canvas.addEventListener('pointerup',e=>{lookDragging=false;down=null;if(moved<8){raycaster.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hits=raycaster.intersectObjects(targets.filter(m=>state.place==='cockpit'?m.parent===cockpit:m.parent!==cockpit));if(hits.length)action(hits[0].object.userData.corpoId)}});canvas.addEventListener('pointercancel',()=>{down=null;lookDragging=false});
window.addEventListener('keydown',e=>{if($('mapDialog').open||$('infoDialog').open)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e'&&state.hover)action(state.hover);if(e.key.toLowerCase()==='m')$('mapDialog').showModal();if(e.key==='Escape'){keys.clear();closeInfo()}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
let joy={x:0,y:0};const j=$('joystick');j.addEventListener('pointerdown',e=>{j.setPointerCapture(e.pointerId);updateJoy(e)});j.addEventListener('pointermove',e=>{if(j.hasPointerCapture(e.pointerId))updateJoy(e)});function updateJoy(e){const r=j.getBoundingClientRect(),x=THREE.MathUtils.clamp((e.clientX-r.left-r.width/2)/35,-1,1),y=THREE.MathUtils.clamp((e.clientY-r.top-r.height/2)/35,-1,1);joy={x,y};$('thumb').style.transform=`translate(${x*26}px,${y*26}px)`}for(const evt of ['pointerup','pointercancel','lostpointercapture'])j.addEventListener(evt,()=>{joy={x:0,y:0};$('thumb').style.transform=''});$('touchInteract').onclick=()=>{if(state.hover)action(state.hover);else $('mapDialog').showModal()};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let elapsed=0;function frame(){const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;for(const p of props){p.rotation.y+=dt*.16}for(let i=0;i<pads.length;i++)pads[i].material.color.setHSL(.47,.5,.5+Math.sin(elapsed*1.5+i)*.1);
if(renderer.xr.isPresenting){xrControls.atualizar(dt);const left=xrControls.maoEsquerda;if(left?.gamepad&&left.controller.visible){if(!menu.conteudo)menu.mostrar({titulo:'Escola',botoes:[{id:'map',rotulo:'Mapa'},{id:'tower',rotulo:'Torre'},{id:'home',rotulo:'Pátio'}]});left.grip.getWorldPosition(v);v.y+=.2;menu.mesh.position.copy(rig.worldToLocal(v.clone()));menu.mesh.lookAt(getHead())}else menu.esconder()}
else if(state.mode==='overview')orbit.update();else if(state.mode==='walk'&&!$('mapDialog').open&&!$('infoDialog').open){let mx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joy.x,my=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0)-joy.y;const len=Math.max(1,Math.hypot(mx,my));mx/=len;my/=len;const speed=state.place==='cockpit'?0:(keys.has('shift')?5.5:3.2);v.set(-Math.sin(yaw)*my+Math.cos(yaw)*mx,0,-Math.cos(yaw)*my-Math.sin(yaw)*mx).multiplyScalar(dt*speed);const p=camera.position.clone().add(v);if(walkable(p))camera.position.copy(p);raycaster.setFromCamera(new THREE.Vector2(0,0),camera);raycaster.far=15;const h=raycaster.intersectObjects(targets.filter(m=>state.place==='cockpit'?m.parent===cockpit:m.parent!==cockpit));state.hover=h[0]?.object.userData.corpoId||null;$('interactHint').style.display=state.hover?'block':'none';if(state.hover)$('interactHint').textContent=`E · ${ROOMS.find(r=>r.id===state.hover)?.name||({tower:'Visitar a torre',board:'Embarcar',launch:'Lançar foguete'}[state.hover])||'Interagir'}`}
if(state.launchTime&&!renderer.xr.isPresenting){const t=(performance.now()-state.launchTime)/1000;if(t>3){campus.position.y=-Math.min(160,(t-3)*(t-3)*20)}}renderer.render(scene,camera)}
renderer.setAnimationLoop(frame);setupVR();save();updateMission();$('loading').remove();
window.school={getState:()=>({...state,progress,position:getHead().toArray(),render:renderer.info.render}),visitRoom,goTower,board,launch,home};
if(document.modelContext?.registerTool){const tool={name:'visit_school_destination',description:'Move to a classroom, launch tower, or courtyard in the school.',inputSchema:{type:'object',properties:{destination:{type:'string',enum:[...ROOMS.map(r=>r.id),'tower','home']}},required:['destination'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||!([...ROOMS.map(r=>r.id),'tower','home'].includes(input.destination)))throw new Error('Unknown destination');await action(input.destination);return {destination:input.destination}}};try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}
